#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_USER=pi
readonly TARGET_PATH=/home/pi/pi_clock
readonly TARGET_ARCH=arm-unknown-linux-gnueabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/pi_clock

cross build --release --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_USER}@${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_USER}@${TARGET_HOST} ${TARGET_PATH}
