#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_USER=pi
readonly TARGET_PATH=/home/pi/pi_clock
readonly TARGET_ARCH=aarch64-unknown-linux-gnu
readonly SOURCE_PATH=./target/${TARGET_ARCH}/debug/pi_clock

cross build --target=${TARGET_ARCH}
cross test --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_USER}@${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_USER}@${TARGET_HOST} ${TARGET_PATH} --version

echo "Deploy successful"
