#!/usr/bin/env bash

set -eu
set -o pipefail
shopt -s inherit_errexit

function main() {
  local release target_host target_filename args

  target_host=""
  target_filename="pi_clock"
  release="false"
  args=()

  while [[ "${#}" != 0 ]]; do
    case "${1}" in
      --release)
        release="true"
        args+=("--release")
        shift 1
        ;;

      --target|-t)
        target_host="${2}"
        shift 2
        ;;

      --target-filename)
        target_filename="${2}"
        shift 2
        ;;

      "")
        # add all unrecognized arguments to list
        args+=("${1}")
        shift 1
        ;;
    esac
  done

  if [[ -z "${target_host}" ]]; then
      echo "Error: must provide target host with --target/-t"
      exit 1
  fi

  readonly target_arch=aarch64-unknown-linux-gnu

  cross build --target="${target_arch}" --features="rpi-hw" "${args[@]}"
  cross test --target="${target_arch}" --features="rpi-hw" "${args[@]}"

  if [[ "${release}" == "true" ]]; then
    readonly source_path="./target/${target_arch}/release/pi_clock"
  else
    readonly source_path="./target/${target_arch}/debug/pi_clock"
  fi

  readonly target_user=pi
  readonly target_path="/home/pi/${target_filename}"

  rsync ${source_path} ${target_user}@${target_host}:${target_path}
  ssh -t ${target_user}@${target_host} ${target_path} --version

  echo "Deploy successful"
}

main "${@:-}"
